export const HOME = '/';
export const REGISTER = '/register';
export const SIGN_IN = '/signin';
export const SIGN_OUT = '/signout';
export const ACCOUNT = '/account';
//export const ADMIN = '/admin';
export const PW_FORGET = '/pw-forget';
export const NOTES = '/notes';
export const TRASH = '/trash'; // need to add a trashed notes page
export const TEST = '/test';